from sam import Sam

sam = Sam()

print("Stamina:")
print(sam.stamina)
print("Happiness:")
print(sam.happiness)
sam.code(value=3)
print("Sam has been coding at TIY. Coding ability + 3!")
sam.eat(value=2)
print("Sam has eaten lunch. Stamina + 2!")
sam.code(value=3)
print("Sam has been coding at TIY. Coding ability + 3!")
sam.play_soccer(value=3)
print("Sam has played a soccer game. Soccer ability + 3!")
print("Stamina:")
print(sam.stamina)
print("Happiness:")
print(sam.happiness)
sam.eat(value=5)
print("Sam ate dinner. Stamina + 5!")
sam.sleep(time=6)
print("Stamina:")
print(sam.stamina)
print("Happiness:")
print(sam.happiness)
print("Sam slept for 6 hours.")
sam.eat(value=3)
print("Sam has eaten breakfast. Stamina + 3!")
sam.code(value=2)
print("Sam has been coding at TIY. Coding ability + 2!")
sam.play_softball(value=4)
print("Sam has played a softball game. Softball ability + 4!")
print("Stamina:")
print(sam.stamina)
print("Happiness:")
print(sam.happiness)
sam.run(time=4)
print("Sam has gone for a run. Stamina - 6!")
sam.eat(value=2)
print("Sam ate dinner. Stamina + 2!")
sam.code(value=4)
print("Sam has been coding at Home. Coding ability + 4!")
print("end of simulation")

print("Stamina:")
print(sam.stamina)
print("Happiness:")
print(sam.happiness)
print("Soccer ability:")
print(sam.soccer_ability)
print("Softball ability:")
print(sam.softball_ability)
print("Coding ability:")
print(sam.coding_ability)
